# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('scifi', models.IntegerField(default=0)),
                ('action', models.IntegerField(default=0)),
                ('comedy', models.IntegerField(default=0)),
                ('romance', models.IntegerField(default=0)),
                ('fantasy', models.IntegerField(default=0)),
                ('family', models.IntegerField(default=0)),
                ('horror', models.IntegerField(default=0)),
                ('avgIncome', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActorsVsDirectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieNum', models.IntegerField(default=0)),
                ('income', models.IntegerField(default=100000)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Actors')),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('scifi', models.IntegerField(default=0)),
                ('action', models.IntegerField(default=0)),
                ('comedy', models.IntegerField(default=0)),
                ('romance', models.IntegerField(default=0)),
                ('fantasy', models.IntegerField(default=0)),
                ('family', models.IntegerField(default=0)),
                ('horror', models.IntegerField(default=0)),
                ('avgIncome', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='actorsvsdirectors',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Directors'),
        ),
    ]
